// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbWajxSsxgccNCs1VC6U_XwktfZ4ik5AA',
    appId: '1:54308082917:web:ee038f9f9768435271700c',
    messagingSenderId: '54308082917',
    projectId: 'medshi',
    authDomain: 'medshi.firebaseapp.com',
    storageBucket: 'medshi.firebasestorage.app',
    measurementId: 'G-BZ02QXV2B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6awIWonWu6eZX2NJWP_D4fOvLaKjxLFI',
    appId: '1:54308082917:android:47a379e94ea70e2971700c',
    messagingSenderId: '54308082917',
    projectId: 'medshi',
    storageBucket: 'medshi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5uG2ynD2G8OaRWFgKSrBbaVoXQp5XRU',
    appId: '1:54308082917:ios:5b2529d56cdea91471700c',
    messagingSenderId: '54308082917',
    projectId: 'medshi',
    storageBucket: 'medshi.firebasestorage.app',
    iosBundleId: 'com.example.medshift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn5uG2ynD2G8OaRWFgKSrBbaVoXQp5XRU',
    appId: '1:54308082917:ios:5b2529d56cdea91471700c',
    messagingSenderId: '54308082917',
    projectId: 'medshi',
    storageBucket: 'medshi.firebasestorage.app',
    iosBundleId: 'com.example.medshift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbWajxSsxgccNCs1VC6U_XwktfZ4ik5AA',
    appId: '1:54308082917:web:7b92b03ea106059a71700c',
    messagingSenderId: '54308082917',
    projectId: 'medshi',
    authDomain: 'medshi.firebaseapp.com',
    storageBucket: 'medshi.firebasestorage.app',
    measurementId: 'G-ZJQWPJQKLK',
  );

}